import { Link, useParams } from 'react-router-dom'

const pages: Record<string, { eyebrow: string; title: string; intro: string; sections: Array<{title:string; body:string}> }> = {
  about: { eyebrow:'ABOUT VELOURA', title:'A women-first fashion destination', intro:'Veloura is a curated commerce experience built around fashion, beauty and accessories for women, with a multi-source catalog and a focus on clean discovery.', sections:[{title:'Our point of view',body:'We favour strong product imagery, simple navigation, useful filters and a calmer editorial aesthetic over noisy marketplace design.'},{title:'The catalog',body:'Veloura combines multiple public product feeds and a curated reserve, then applies women-only classification, category validation, broken-image filtering and deduplication before products reach the storefront.'}] },
  shipping: { eyebrow:'CUSTOMER CARE', title:'Shipping', intro:'Shipping information for Veloura’s current sandbox-fulfilment checkout.', sections:[{title:'Delivery charges',body:'Standard delivery is shown as free above ₹1,499. Final delivery messaging appears in cart and checkout.'},{title:'Delivery estimates',body:'Product pages accept an Indian 6-digit pincode for availability UI. Veloura does not yet dispatch physical shipments, so courier ETAs remain estimates until a fulfilment provider is activated.'},{title:'Order tracking',body:'Persistent Veloura orders can be viewed in My Veloura and tracked by their order ID. Status milestones remain sandboxed until fulfilment is activated.'}] },
  returns: { eyebrow:'CUSTOMER CARE', title:'Returns & refunds', intro:'The return rules represented by the current Veloura commerce experience.', sections:[{title:'30-day window',body:'The storefront represents a 30-day return window for eligible items. Physical return processing begins only after fulfilment activation.'},{title:'Condition',body:'Items should be unused, unworn and returned with original tags and packaging where applicable.'},{title:'Exceptions',body:'Beauty, intimate, personalised and hygiene-sensitive categories may require stricter return rules in a real production store.'},{title:'Refunds',body:'Payments remain sandboxed, so no real refund is sent to a card, bank or UPI provider today.'}] },
  'size-guide': { eyebrow:'FIT & SIZING', title:'Veloura size guide', intro:'A general reference for women’s clothing and footwear. Brand measurements should always take priority when available.', sections:[{title:'Apparel',body:'XS commonly aligns around 32 in bust / 25 in waist, S around 34 / 27, M around 36 / 29, L around 38 / 31, and XL around 40 / 33. These are approximate guide values.'},{title:'Footwear',body:'Our general EU range runs from 36 to 41. Foot length is a better reference than label alone when brands vary.'},{title:'Accessories',body:'Bags, jewellery, watches, sunglasses and most beauty products are treated as One Size unless the source provides dimensions.'}] },
  privacy: { eyebrow:'LEGAL', title:'Privacy', intro:'Veloura separates guest browser state from signed-in account data and limits cloud access with row-level security.', sections:[{title:'Local shopping state',body:'Guest bag, wishlist, recently viewed items and recent searches are stored in browser storage. When you sign in, eligible Veloura shopping state is merged into your account and synchronized through the isolated Veloura database schema.'},{title:'Catalog requests',body:'Public catalog sources are requested to populate the storefront. Veloura does not intentionally send your cart or wishlist to those providers.'},{title:'Payments',body:'Card and UPI fields are sandbox-only and are not persisted by Veloura. Account data uses authenticated, account-scoped database policies.'}] },
  terms: { eyebrow:'LEGAL', title:'Terms of use', intro:'Veloura provides a functioning account, catalog and order-record experience while payment processing and physical fulfilment remain sandboxed.', sections:[{title:'Product information',body:'Prices, availability, ratings and imagery can originate from public demo or catalog APIs and may not represent a purchasable listing.'},{title:'Orders',body:'Checkout creates a persistent Veloura order record, but it does not charge a payment method or create a physical shipment until production payment and fulfilment providers are activated.'},{title:'Third-party sources',body:'Some catalog items include a source reference so the origin of externally supplied product data remains transparent.'}] },
  faq: { eyebrow:'HELP CENTRE', title:'Frequently asked questions', intro:'Quick answers about shopping, accounts, catalog data and the current Veloura commerce experience.', sections:[{title:'Is Veloura a women-only store?',body:'Yes. The storefront taxonomy, search filtering and catalog quality gates are designed around women’s fashion, beauty and accessories.'},{title:'Why do some products have more photos than others?',body:'Different catalog providers expose different gallery depth. Veloura uses genuine distinct images where available and does not fabricate alternate product photos.'},{title:'Can I really place an order?',body:'You can create a persistent Veloura order and track it in your account, but payment and physical fulfilment remain sandboxed, so no real charge or shipment occurs.'},{title:'Why can a category size change?',body:'Veloura combines live public catalog feeds. Quality filters can remove duplicates, broken images or misclassified products, so collection size can change as sources change.'}] },
  contact: { eyebrow:'CONTACT', title:'Talk to Veloura', intro:'Need help with the experience or want to report a catalog issue?', sections:[{title:'Customer experience',body:'Use the Help Centre pages for shipping, returns, sizing and catalog questions.'},{title:'Email',body:'For the demo project, contact details should be connected to a real support inbox before any public retail launch.'},{title:'Report a product issue',body:'If a product is in the wrong category, has a broken image or looks duplicated, that is treated as a catalog-quality bug and should be removed at the source adapter or manager layer.'}] },
}

export default function HelpPage() {
  const { slug = 'faq' } = useParams()
  const page = pages[slug] ?? pages.faq
  return <div className="help-page container">
    <div className="breadcrumbs"><Link to="/">Home</Link><span>/</span><Link to="/help/faq">Help</Link><span>/</span><span>{page.title}</span></div>
    <header><span className="eyebrow">{page.eyebrow}</span><h1>{page.title}</h1><p>{page.intro}</p></header>
    <div className="help-layout"><aside>{Object.entries(pages).map(([key,value]) => <Link className={slug === key ? 'active' : ''} key={key} to={`/help/${key}`}>{value.title}</Link>)}</aside><main>{page.sections.map((section) => <section key={section.title}><h2>{section.title}</h2><p>{section.body}</p></section>)}</main></div>
  </div>
}
