import { Link, useParams } from 'react-router-dom'

const pages: Record<string, { eyebrow: string; title: string; intro: string; sections: Array<{title:string; body:string}> }> = {
  about: { eyebrow:'ABOUT VELOURA', title:'A women-first fashion destination', intro:'Veloura is a curated commerce experience built around fashion, beauty and accessories for women, with a multi-source catalog and a focus on clean discovery.', sections:[{title:'Our point of view',body:'We favour strong product imagery, simple navigation, useful filters and a calmer editorial aesthetic over noisy marketplace design.'},{title:'The catalog',body:'Veloura combines multiple public product feeds and a curated reserve, then applies women-only classification, category validation, broken-image filtering and deduplication before products reach the storefront.'}] },
  shipping: { eyebrow:'CUSTOMER CARE', title:'Shipping', intro:'Shipping information for the Veloura demo checkout experience.', sections:[{title:'Delivery charges',body:'Standard delivery is shown as free above ₹1,499. Final delivery messaging appears in cart and checkout.'},{title:'Delivery estimates',body:'Product pages accept an Indian 6-digit pincode for availability UI. Because Veloura is a portfolio commerce experience rather than a live fulfilment operation, real courier ETAs are not promised.'},{title:'Order tracking',body:'Use the Account area to view the demo order journey and tracking interface.'}] },
  returns: { eyebrow:'CUSTOMER CARE', title:'Returns & refunds', intro:'A simple, customer-friendly returns policy for the Veloura shopping experience.', sections:[{title:'30-day window',body:'Eligible items can be marked for return within 30 days in this demo experience.'},{title:'Condition',body:'Items should be unused, unworn and returned with original tags and packaging where applicable.'},{title:'Exceptions',body:'Beauty, intimate, personalised and hygiene-sensitive categories may require stricter return rules in a real production store.'},{title:'Refunds',body:'No real payment is processed by Veloura today, so refund actions are represented in the interface rather than sent to a payment provider.'}] },
  'size-guide': { eyebrow:'FIT & SIZING', title:'Veloura size guide', intro:'A general reference for women’s clothing and footwear. Brand measurements should always take priority when available.', sections:[{title:'Apparel',body:'XS commonly aligns around 32 in bust / 25 in waist, S around 34 / 27, M around 36 / 29, L around 38 / 31, and XL around 40 / 33. These are approximate guide values.'},{title:'Footwear',body:'Our general EU range runs from 36 to 41. Foot length is a better reference than label alone when brands vary.'},{title:'Accessories',body:'Bags, jewellery, watches, sunglasses and most beauty products are treated as One Size unless the source provides dimensions.'}] },
  privacy: { eyebrow:'LEGAL', title:'Privacy', intro:'Veloura keeps the current demo intentionally lightweight.', sections:[{title:'Local shopping state',body:'Bag, wishlist, recently viewed items and recent searches are stored in your browser local storage so the experience can persist across refreshes.'},{title:'Catalog requests',body:'Public catalog sources are requested to populate the storefront. Veloura does not intentionally send your cart or wishlist to those providers.'},{title:'Payments',body:'The demo checkout does not store real card data.'}] },
  terms: { eyebrow:'LEGAL', title:'Terms of use', intro:'Veloura is an API-backed portfolio commerce experience and is not currently operating as a live retailer.', sections:[{title:'Product information',body:'Prices, availability, ratings and imagery can originate from public demo or catalog APIs and may not represent a purchasable listing.'},{title:'Orders',body:'Checkout and order confirmation are demonstration flows. No binding retail order is created.'},{title:'Third-party sources',body:'Some catalog items include a source reference so the origin of externally supplied product data remains transparent.'}] },
  faq: { eyebrow:'HELP CENTRE', title:'Frequently asked questions', intro:'Quick answers about shopping, catalog data and the Veloura demo experience.', sections:[{title:'Is Veloura a women-only store?',body:'Yes. The storefront taxonomy, search filtering and catalog quality gates are designed around women’s fashion, beauty and accessories.'},{title:'Why do some products have more photos than others?',body:'Different catalog providers expose different gallery depth. Veloura uses genuine distinct images where available and does not fabricate alternate product photos.'},{title:'Can I really place an order?',body:'The shopping flow is interactive, but checkout is a safe demo and does not process a real payment.'},{title:'Why can a category size change?',body:'Veloura combines live public catalog feeds. Quality filters can remove duplicates, broken images or misclassified products, so collection size can change as sources change.'}] },
  contact: { eyebrow:'CONTACT', title:'Talk to Veloura', intro:'Need help with the experience or want to report a catalog issue?', sections:[{title:'Customer experience',body:'Use the Help Centre pages for shipping, returns, sizing and catalog questions.'},{title:'Email',body:'For the demo project, contact details should be connected to a real support inbox before any public retail launch.'},{title:'Report a product issue',body:'If a product is in the wrong category, has a broken image or looks duplicated, that is treated as a catalog-quality bug and should be removed at the source adapter or manager layer.'}] },
}

export default function HelpPage() {
  const { slug = 'faq' } = useParams()
  const page = pages[slug] ?? pages.faq
  return <div className="help-page container">
    <div className="breadcrumbs"><Link to="/">Home</Link><span>/</span><Link to="/help/faq">Help</Link><span>/</span><span>{page.title}</span></div>
    <header><span className="eyebrow">{page.eyebrow}</span><h1>{page.title}</h1><p>{page.intro}</p></header>
    <div className="help-layout"><aside>{Object.entries(pages).map(([key,value]) => <Link className={slug === key ? 'active' : ''} key={key} to={`/help/${key}`}>{value.title}</Link>)}</aside><main>{page.sections.map((section) => <section key={section.title}><h2>{section.title}</h2><p>{section.body}</p></section>)}</main></div>
  </div>
}
