import { useState, type FormEvent } from 'react'
import { Heart, HelpCircle, Menu, Search, ShoppingBag, Smartphone, Truck, UserRound, X } from 'lucide-react'
import { Link, NavLink, Outlet, useNavigate } from 'react-router-dom'
import { HEADER_NAV, WOMEN_CATEGORIES } from '../data/catalog'
import { useShop } from '../store/ShopContext'

export default function Layout() {
  const [menuOpen, setMenuOpen] = useState(false)
  const [mobileSearchOpen, setMobileSearchOpen] = useState(false)
  const [query, setQuery] = useState('')
  const { cartCount, wishlist } = useShop()
  const navigate = useNavigate()
  const submitSearch = (e: FormEvent) => { e.preventDefault(); const next = query.trim(); navigate(next ? `/shop?q=${encodeURIComponent(next)}` : '/shop'); setMobileSearchOpen(false); setMenuOpen(false) }

  return <div className="app-shell"><div className="offer-ribbon"><span>WOMEN'S FASHION ONLY</span><strong>EXTRA 10% OFF ON YOUR FIRST ORDER · CODE: HELLOVELOURA</strong><span>FREE SHIPPING ABOVE ₹1,499</span></div><div className="utility-bar container-wide"><span>India</span><div><a href="#app"><Smartphone size={13} /> Download app</a><a href="#help"><HelpCircle size={13} /> Help</a><Link to="/account"><Truck size={13} /> Track order</Link></div></div><header className="site-header"><div className="header-inner container-wide"><button className="icon-button mobile-only" aria-label="Open menu" onClick={() => setMenuOpen(true)}><Menu size={23} /></button><Link className="brand" to="/">VELOURA<span>WOMEN</span></Link><form className="desktop-search" onSubmit={submitSearch}><Search size={19} /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search for dresses, tops, bags, beauty and more" /><button type="submit">Search</button></form><div className="header-actions"><button className="icon-button mobile-only" aria-label="Search" onClick={() => setMobileSearchOpen((value) => !value)}><Search size={21} /></button><Link className="header-action hide-small" aria-label="Account" to="/account"><UserRound size={20} /><span>Profile</span></Link><Link className="header-action badge-wrap" aria-label="Wishlist" to="/wishlist"><Heart size={20} /><span className="hide-label-mobile">Wishlist</span>{wishlist.length > 0 && <span className="badge">{wishlist.length}</span>}</Link><Link className="header-action badge-wrap" aria-label="Cart" to="/cart"><ShoppingBag size={20} /><span className="hide-label-mobile">Bag</span>{cartCount > 0 && <span className="badge">{cartCount}</span>}</Link></div></div></header><nav className="category-nav"><div className="category-nav-inner container-wide"><NavLink to="/shop" end>New In</NavLink>{HEADER_NAV.map((value) => { const category = WOMEN_CATEGORIES.find((item) => item.value === value); return category ? <NavLink key={value} to={`/shop?category=${value}`}>{category.shortLabel || category.label}</NavLink> : null })}<Link className="sale-nav" to="/shop?sort=discount">Sale</Link></div></nav>
  {mobileSearchOpen && <div className="mobile-search-panel"><form onSubmit={submitSearch}><Search size={19} /><input autoFocus value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search women's fashion" /><button type="button" className="icon-button" onClick={() => setMobileSearchOpen(false)}><X size={19} /></button></form></div>}
  {menuOpen && <div className="mobile-menu-backdrop" onClick={() => setMenuOpen(false)}><aside className="mobile-menu" onClick={(e) => e.stopPropagation()}><div className="mobile-menu-head"><span className="brand">VELOURA<span>WOMEN</span></span><button className="icon-button" onClick={() => setMenuOpen(false)}><X /></button></div><form className="menu-search" onSubmit={submitSearch}><Search size={18} /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search women's fashion" /></form><p className="menu-label">Shop women</p><Link onClick={() => setMenuOpen(false)} to="/shop">New in</Link>{WOMEN_CATEGORIES.map((category) => <Link key={category.value} onClick={() => setMenuOpen(false)} to={`/shop?category=${category.value}`}>{category.label}</Link>)}<div className="menu-divider" /><Link onClick={() => setMenuOpen(false)} to="/wishlist">Wishlist</Link><Link onClick={() => setMenuOpen(false)} to="/account">My account</Link></aside></div>}
  <main><Outlet /></main><footer className="footer"><div className="footer-grid container-wide"><div className="footer-about"><span className="brand footer-brand">VELOURA<span>WOMEN</span></span><p>A women-only fashion destination for everyday style, occasion dressing, accessories and beauty.</p><div className="app-badges" id="app"><button>▶ Google Play</button><button> App Store</button></div></div><div><h4>Online shopping</h4><Link to="/shop?category=womens-dresses">Dresses</Link><Link to="/shop?category=womens-tops">Tops</Link><Link to="/shop?category=womens-ethnicwear">Ethnic wear</Link><Link to="/shop?category=womens-shoes">Footwear</Link><Link to="/shop?category=womens-beauty">Beauty</Link></div><div><h4>Customer policies</h4><a href="#shipping">Shipping</a><a href="#returns">Returns & refunds</a><a href="#size">Size guide</a><a href="#privacy">Privacy</a><a href="#terms">Terms</a></div><div id="help"><h4>Useful links</h4><Link to="/account">Track orders</Link><Link to="/wishlist">Wishlist</Link><a href="mailto:hello@veloura.example">Contact us</a><a href="#faq">FAQ</a></div><div className="footer-newsletter"><h4>Get the good stuff first</h4><p>New drops, big offers and editor picks—straight to your inbox.</p><form className="newsletter" onSubmit={(e) => e.preventDefault()}><input type="email" placeholder="Email address" required /><button>Join</button></form><small>By joining, you agree to receive Veloura marketing emails.</small></div></div><div className="footer-assurance container-wide"><div><strong>100% ORIGINAL</strong><span>Curated catalog experience</span></div><div><strong>EASY RETURNS</strong><span>30-day return window</span></div><div><strong>SECURE CHECKOUT</strong><span>Demo payment flow, no card data stored</span></div></div><div className="footer-bottom container-wide"><span>© 2026 Veloura Women</span><span>Portfolio commerce experience · API-backed catalog</span></div></footer></div>
}
